name: generic-checks

on: [push, pull_request]
  #push:
    #branches-ignore:
      #- master
      #- dev
      #

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo xtask setup
      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo xtask ci
